name: on-push-do-doco
on: 
  push:
jobs:
  release:
    runs-on: windows-latest
    steps:
    - name: Get env vars
      run: |
        echo HOME              = $HOME
        echo GITHUB_ACTION     = $GITHUB_ACTION
        echo GITHUB_ACTOR      = $GITHUB_ACTOR
        echo GITHUB_ACTIONS    = $GITHUB_ACTIONS
        echo GITHUB_REPOSITORY = $GITHUB_REPOSITORY
        echo GITHUB_EVENT_NAME = $GITHUB_EVENT_NAME
        echo GITHUB_EVENT_PATH = $GITHUB_EVENT_PATH
        echo GITHUB_WORKSPACE  = $GITHUB_WORKSPACE
        echo GITHUB_SHA        = $GITHUB_SHA
        echo GITHUB_REF        = $GITHUB_REF
        echo tag               = ${GITHUB_REF:10}
        echo repo              = ${GITHUB_REPOSITORY#*/}
        echo owner             = ${GITHUB_REPOSITORY%/*} 
      shell: bash
    - uses: actions/checkout@v2
    - name: Run MarkdownSnippets
      run: | 
        dotnet tool install --global MarkdownSnippets.Tool
        mdsnippets ${GITHUB_WORKSPACE}
      shell: bash
    - name: Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff-index --quiet HEAD || git commit -m "Doco changes" -a
        remote="https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
        echo "remote $remote";
        git push "${remote_repo}" HEAD:${GITHUB_REF} || echo "nothing to commit"
      shell: bash
