name: on-tag-close-milestone
on: 
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
jobs:
  close-milestone:
    runs-on: windows-latest
    steps:
    - name: install GitReleaseManager choco
      run: choco install gitreleasemanager.portable -y
    - run: 'gitreleasemanager create -m ${GITHUB_REPOSITORY:11} --token ${{secrets.GITHUB_TOKEN}} -o ${GITHUB_REPOSITORY:~0,10} -r ${GITHUB_REPOSITORY:11}'
    - run: 'gitreleasemanager close -m ${GITHUB_REPOSITORY:11} --token ${{secrets.GITHUB_TOKEN}} -o ${GITHUB_REPOSITORY:~0,10} -r ${GITHUB_REPOSITORY:11}'
