name: on-tag-close-milestone
on: 
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
jobs:
  close-milestone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Set tag name
      run: echo ::set-output name=tag::${GITHUB_REF:10}
    - name: Set repo owner
      run: echo ::set-output name=owner::${GITHUB_REPOSITORY:~0,10}
    - name: Set repo name
      run: echo ::set-output name=repo::${GITHUB_REPOSITORY:11}
    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0
    - run: dotnet gitreleasemanager create -m ${{steps.vars.outputs.tag}} --token ${{secrets.GITHUB_TOKEN}} -o ${{steps.vars.outputs.owner}} -r ${{steps.vars.outputs.repo}}
    - run: dotnet gitreleasemanager close -m ${{steps.vars.outputs.tag}} --token ${{secrets.GITHUB_TOKEN}} -o ${{steps.vars.outputs.owner}} -r ${{steps.vars.outputs.repo}}
